---
services:
  certdns:
    image: alpine:3.20
    container_name: certdns
    # no user: ...  (starts as root for package bootstrap)
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./data:/data
      - ./scripts:/app
      - ./config:/config
    entrypoint: ["/app/boot.sh"]
    restart: unless-stopped
    environment:
      - DEDYN_TOKEN=ENTERME
